[package]
name = "banana"
version = "4.4.3"
edition = "2021"
#authors = "n_emperor"

[dependencies]
sha2 = "0.10.8"
sha3 = "0.10.8"
colored = "3.0.0"
md-5 = "0.10.6"
regex = "1.11.1"
rayon = "1.10.0"
lazy_static = "1.5.0"

